name: octobase_flutter
description: "Connect OctoberCMS with Flutter using Octobase Plugin."
version: 1.0.2
homepage: https://dilexusit.com
repository: https://github.com/chaturadilan/octobase-flutter


environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pluralize: ^0.0.8
  shared_preferences: ^2.2.2

dev_dependencies:

  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: